@import "@/styles/index.scss";
import { config } from "@/helpers/config";


export const metadata = {
  title: {
    template: `%s | ${config.project.name}`
    default:${config.project.name}
  }
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
